image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - Surendrajat.apklab@0.8.1:OhdgOyLTJ3kU9QUlsWLIlQ==
    - mhutchie.git-graph@1.26.0:m8EvA1owa1dL2R6+Swieyg==
    - humao.rest-client@0.24.2:tiNIwP71m33jcKqZcyO2EQ==
    - mitchdenny.ecdc@1.3.0:OtulJCyxdGkGI+EYhjDslg==
    - ritwickdey.LiveServer@5.6.1:5Mhl1RgVVDcIym163x8r+w==
    - eg2.vscode-npm-script@0.3.11:Np1+d2YoqckGfeIuPylSEw==
    - CoenraadS.bracket-pair-colorizer@1.0.61:+jQByqALW0iXkhpd2yzYzQ==